name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installiere Python (falls nicht vorhanden)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installiere Python-Abhängigkeiten
        run: pip install pyyaml

      - name: YAML-Datei generieren
        run: |
          python .github/scripts/generate_yaml.py

      - name: Änderungen committen und pushen
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add MeinBlazorProjekt/wwwroot/images.yaml
          git commit -m "Automatische YAML-Generierung aus wwwroot" || echo "Keine Änderungen zum Commit"
          git push

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore and Build Blazor WASM
        run: |
          cd MeinBlazorProjekt
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o release
          ls -la release/wwwroot # <-- Zeigt an, ob wwwroot existiert
          mv release/wwwroot ../wwwroot

      - name: Verify wwwroot exists
        run: ls -la wwwroot # <-- Prüft, ob die Dateien tatsächlich da sind

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./wwwroot
