name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore and Build Blazor WASM
        run: |
          cd MeinBlazorProjekt
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o release
          ls -la release/wwwroot # <-- Zeigt an, ob wwwroot existiert
          mv release/wwwroot ../wwwroot

      - name: Verify wwwroot exists
        run: ls -la wwwroot # <-- Prüft, ob die Dateien tatsächlich da sind

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./wwwroot
